language: node_js
node_js:
  - "14"
cache:
  directories:
    - node_modules

branches:
  only:
    - master
    - linting_and_travis

jobs:
  include:
    - stage: Lint, Test, Build
      name: Lint
      script:
        - npm install
        - cd chitchat
        - npm install
        - cd ../
        - npm run lint
    - name: Test
      script:
        - npm install
        - npm run test-server
    - name: Build
      script:
        - npm install
        - cd chitchat
        - npm install
        - npm run build
