apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
  labels:
    app: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name: project
          image: project
          imagePullPolicy: "Never"
          ports:
            - containerPort: 5001

---
apiVersion: v1
kind: Service
metadata:
  name: project
spec:
  selector:
    app: project
  ports:
    - port: 5001
