name: Cypress Tests

on: [push]

env:
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: setenv
        run: export JWT_SECRET=${{ secrets.JWT_SECRET }}
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.2 # use the explicit version number
        with:
          build: npm run build
          start: npm start
